version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python -m venv venv && source venv/bin/activate && pip install poetry && poetry install && poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"