version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: tdd
    ports:
      - 5432:5432

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn api.main:app --host 0.0.0.0 --reload --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"