name: Appwords CI/CD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: Linting
        run: flake8 --ignore=E501 .

      - name: Running tests
        run: python -m unittest discover -s api.tests

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run:  devtomio/action-railway@v1.1.4
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
